[metadata]
name = "Gruvbox Material Hard dark"
author = "sainnhe"
origin_url = "https://github.com/sainnhe/gruvbox-material"

[colors]
foreground = "#d4be98"
background = "#1d2021"
cursor_bg = "#d4be98"
cursor_border = "#d4be98"
cursor_fg = "#1d2021"
selection_bg = "#d4be98"
selection_fg = "#3c3836"

ansi = ["#1d2021", "#ea6962", "#a9b665", "#d8a657", "#7daea3", "#d3869b", "#89b482", "#d4be98"]
brights = ["#eddeb5", "#ea6962", "#a9b665", "#d8a657", "#7daea3", "#d3869b", "#89b482", "#d4be98"]
